version: '3.8'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.4
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - dev_localhost
    environment:
      MLFLOW_TRACKING_URI: postgresql://admin:admin@postgres:5432/database_dev
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      BUCKET_NAME: mlflow
    depends_on:
      - postgres
      - minio

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - dev_localhost

  postgres:
    image: postgres:14.18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev_localhost

  minio:
    image: minio/minio:latest
    container_name: mlflow-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9003:9000"
      - "9002:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - dev_localhost

volumes:
  postgres-data:
  minio-data:
  sonarqube_extensions:

networks:
  dev_localhost:
